package cn.com.checknull.entity;

// Generated 2015-3-17 16:18:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLogLogin generated by hbm2java
 */
@Entity
@Table(name="t_log_login")
public class TLogLogin implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 7319253577325275670L;
	private Long id;
	private String loginName;
	private String operatorName;
	private Long operatorId;
	private Integer type;
	private Integer result;
	private String description;
	private String loginIp;
	private Date time = new Date();

	public TLogLogin() {
	}

	public TLogLogin(String loginName, String operatorName, Long operatorId,
			Integer type, Integer result, String description, String loginIp,
			Date time) {
		this.loginName = loginName;
		this.operatorName = operatorName;
		this.operatorId = operatorId;
		this.type = type;
		this.result = result;
		this.description = description;
		this.loginIp = loginIp;
		this.time = time;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID",length=20,nullable=false,unique=true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="LOGIN_NAME",length=32,nullable=true)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	@Column(name="OPERATOR_NAME",length=32,nullable=true)
	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}
	@Column(name="OPERATOR_ID",length=20,nullable=true)
	public Long getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}
	@Column(name="TYPE",length=2,nullable=true)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	@Column(name="RESULT",length=2,nullable=true)
	public Integer getResult() {
		return this.result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}
	@Column(name="DESCRIPTION",nullable=true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Column(name="LOGIN_IP",length=32,nullable=true)
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="TIME", nullable=true)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TLogLogin other = (TLogLogin) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
