package cn.com.checknull.entity;

// Generated 2015-2-28 11:52:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TOperator generated by hbm2java
 */
@Entity
@Table(name="t_operator")
public class TOperator implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 8151988987778006043L;
	private Long id;
	private Integer gender;
	private String loginName;
	private String password;
	private String realName;
	private String phone;
	private String mobile;
	private String fax;
	private String email;
	private String msn;
	private String qq;
	private Integer errorTimes = 0;
	private Date updateTime;
	private String loginIp;
	private Date loginTime;
	private Date createTime = new Date();
	private Integer isPlatoperator;
	private Integer status;
	private Long cpCode;
	public TOperator() {
	}

	public TOperator(String loginName) {
		this.loginName = loginName;
	}

	public TOperator(Integer gender, String loginName, String password,
			String realName, String phone, String mobile, String fax,
			String email, String msn, String qq, Integer errorTimes,
			Date updateTime, String loginIp, Date loginTime, Date createTime,
			Integer isPlatoperator, Integer status, Long cpCode) {
		this.gender = gender;
		this.loginName = loginName;
		this.password = password;
		this.realName = realName;
		this.phone = phone;
		this.mobile = mobile;
		this.fax = fax;
		this.email = email;
		this.msn = msn;
		this.qq = qq;
		this.errorTimes = errorTimes;
		this.updateTime = updateTime;
		this.loginIp = loginIp;
		this.loginTime = loginTime;
		this.createTime = createTime;
		this.isPlatoperator = isPlatoperator;
		this.status = status;
		this.cpCode = cpCode;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID",length=20,nullable=false,unique=true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="GENDER",length=11,nullable=true)
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}
	@Column(name="LOGIN_NAME",length=32,nullable=true)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	@Column(name="PASSWORD",length=32,nullable=true)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name="REAL_NAME",length=32,nullable=true)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}
	@Column(name="PHONE",length=32,nullable=true)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	@Column(name="MOBILE",length=32,nullable=true)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	@Column(name="FAX",length=32,nullable=true)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}
	@Column(name="EMAIL",length=32,nullable=true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Column(name="MSN",length=32,nullable=true)
	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}
	@Column(name="QQ",length=32,nullable=true)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}
	@Column(name="ERROR_TIMES",length=2,nullable=true)
	public Integer getErrorTimes() {
		return this.errorTimes;
	}

	public void setErrorTimes(Integer errorTimes) {
		this.errorTimes = errorTimes;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="UPDATE_TIME",nullable=true)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name="LOGIN_IP",length=15,nullable=true)
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="LOGIN_TIME",nullable=true)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREATE_TIME",nullable=true)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Column(name="IS_PLATOPERATOR",length=11,nullable=true)
	public Integer getIsPlatoperator() {
		return this.isPlatoperator;
	}
	
	public void setIsPlatoperator(Integer isPlatoperator) {
		this.isPlatoperator = isPlatoperator;
	}
	@Column(name="STATUS",length=2,nullable=true)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	@Column(name="CP_CODE",length=20,nullable=true)
	public Long getCpCode() {
		return cpCode;
	}

	public void setCpCode(Long cpCode) {
		this.cpCode = cpCode;
	}

}
