package cn.com.checknull.entity;

// Generated 2015-3-2 14:20:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSyspriv generated by hbm2java
 */
@Entity
@Table(name="t_syspriv")
public class TSyspriv implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 6545739685137155618L;
	private long id;
	private String code;
	private String name;
	private String iconCls;
	private String method;
	private TSysmenu menu;
	private Integer sequence;
	private Date createTime = new Date();
	private Integer status;

	public TSyspriv() {
	}

	public TSyspriv(long id) {
		this.id = id;
	}

	public TSyspriv(long id, String code, String name,
			String iconCls, String method, Integer sequence, 
			Date createTime, Integer status) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.iconCls = iconCls;
		this.method = method;
		this.sequence = sequence;
		this.createTime = createTime;
		this.status = status;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID",length=20,nullable=false,unique=true)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	@Column(name="CODE",length=64,nullable=true)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	@Column(name="NAME",length=128,nullable=true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name="ICON_CLS",length=64,nullable=true)
	public String getIconCls() {
		return iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}
	@Column(name="METHOD",length=64,nullable=true)
	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER,optional=true)
	@JoinColumn(name="MENU_ID")
	public TSysmenu getMenu() {
		return menu;
	}

	public void setMenu(TSysmenu menu) {
		this.menu = menu;
	}

	@Column(name="SEQUENCE",length=11,nullable=true)
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREATE_TIME",nullable=true)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	@Column(name="STATUS",length=2,nullable=true)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
