package cn.com.checknull.entity;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 2015-2-28 11:52:11 by Hibernate Tools 3.4.0.CR1

/**
 * TSysmenu generated by hbm2java
 */
@Entity
@Table(name="t_sysmenu")
public class TSysmenu implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 7500114071288119663L;
	private Long id;
	private String name;
	private String code;
	private String navigateUrl;
	private String icon;
	private TSysmenu parentMenu;
	private Integer level;
	private Integer sequence;
	private Date createTime = new Date();
	private Integer status;
	
	public TSysmenu() {
	}

	public TSysmenu(String name, String navigateUrl, String icon,
			TSysmenu parentMenu, Integer level, Integer sequence, 
			Date createTime, Integer status, String code) {
		this.name = name;
		this.navigateUrl = navigateUrl;
		this.icon = icon;
		this.parentMenu = parentMenu;
		this.level = level;
		this.sequence = sequence;
		this.createTime = createTime;
		this.status = status;
		this.code = code;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID",length=20,nullable=false,unique=true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="NAME",length=128,nullable=true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name="CODE",length=64,nullable=true)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name="NAVIGATE_URL",length=256,nullable=true)
	public String getNavigateUrl() {
		return this.navigateUrl;
	}

	public void setNavigateUrl(String navigateUrl) {
		this.navigateUrl = navigateUrl;
	}
	@Column(name="ICON",length=256,nullable=true)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER,optional=true)
	@JoinColumn(name="PARENT_ID")
	public TSysmenu getParentMenu() {
		return parentMenu;
	}

	public void setParentMenu(TSysmenu parentMenu) {
		this.parentMenu = parentMenu;
	}
	@Column(name="LEVEL",length=11,nullable=true)
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name="SEQUENCE",length=11,nullable=true)
	public Integer getSequence() {
		return this.sequence;
	}

	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREATE_TIME",nullable=true)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name="STATUS",length=2,nullable=true)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
