package cn.com.checknull.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 2015-3-17 16:18:12 by Hibernate Tools 3.4.0.CR1

/**
 * TSysconfig generated by hbm2java
 */
@Entity
@Table(name="t_sysconfig")
public class TSysconfig implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO
	*/ 
	private static final long serialVersionUID = 5741331356522050486L;
	private Long id;
	private String paramName;
	private String paramCode;
	private String paramValue;
	private String description;
	private Date createTime = new Date();
	
	public TSysconfig() {
	}

	public TSysconfig(String paramName, String paramCode, String paramValue,
			String description, Date createTime) {
		this.paramName = paramName;
		this.paramCode = paramCode;
		this.paramValue = paramValue;
		this.description = description;
		this.createTime = createTime;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="ID",length=20,nullable=false,unique=true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@Column(name="PARAM_NAME",length=50,nullable=true)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}
	@Column(name="PARAM_CODE",length=50,nullable=true)
	public String getParamCode() {
		return this.paramCode;
	}

	public void setParamCode(String paramCode) {
		this.paramCode = paramCode;
	}
	@Column(name="PARAM_VALUE",length=255,nullable=true)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}
	@Column(name="DESCRIPTION",nullable=true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREATE_TIME", nullable=true)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
